config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "yelps#search"
  # get 'yelps/search'

  get '/users/:id/yelps/', to: 'yelps#index', as: "user_yelps"
  get '/search', to: 'yelps#search'
  get '/search/yelp', to: 'yelps#index'
  resources 'yelps'
  resources 'profiles'
  # resources 'users'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :yelps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/yelp.rb
class Yelp < ApplicationRecord
 belongs_to :user

	API_HOST = "https://api.yelp.com"
	SEARCH_PATH = "/v3/businesses/search"
	BUSINESS_PATH = "/v3/businesses/"
	TOKEN_PATH = "/oauth2/token"
	GRANT_TYPE = "client_credentials"		
	CLIENT_ID = "Uj4wStxhDH0vywJ7TnFFog"
	CLIENT_SECRET = "lPWGWvhAFSr0fJR5pTwhkgbhXuqjalHmI7lWAeMB8yNtD5wJ08CT0EqeM2eQHaQu"
	SEARCH_LIMIT = 50 #search limit

  def self.search_path(opts={})
		verify_url = "#{API_HOST}#{TOKEN_PATH}"	 # Put the url together
		verify_params = { # Build our params hash
      client_id: CLIENT_ID,
      client_secret: CLIENT_SECRET,
      grant_type: GRANT_TYPE
    }
    verified_response = HTTP.post(verify_url, params: verify_params)
    parsed = verified_response.parse
    "#{parsed['token_type']} #{parsed['access_token']}"
    url = "#{API_HOST}#{SEARCH_PATH}"
    params = {
      term: opts[:term],
      location: opts[:location],
      limit: SEARCH_LIMIT
    }
    response = HTTP.auth("#{parsed['token_type']} #{parsed['access_token']}").get(url, params: params)
    response.parse
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def show
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/yelps_controller.rb
class YelpsController < ApplicationController
  def index
    @user = current_user
    @yelps = @user.yelps
  end

  def new
    @yelp = Yelp.new
  end

  def create
    @yelp = current_user.yelps.build(yelp_params)
    if @yelp.save
      redirect_to request.referer
    end

  end

  
  def search
    if params
       opts = {
        term: params[:term],
        location: params[:location]
     }  
     @response = Yelp.search_path(opts)
      end
    end

    def destroy
      Yelp.find(des_params).destroy
      redirect_to user_yelps_path
    end


    private
    def yelp_params
      params.require(:result).permit(:phone,:address,:name, :price, :image,:review_count)
    end
    def des_params
      params.require(:yelp_id)
    end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/yelps_helper.rb
module YelpsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Never Plan" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top navbar-inverse bg-inverse">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Never Plan', root_path, class:"navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Search", '/search'  %></li>
            <% unless current_user %>
            <li><%= link_to "Login", new_user_session_path  %></li>
            <% else %>
              <li><%= link_to "Profile", '/users/:id/yelps' %></li>
              <li><%= link_to "Logout", destroy_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
         <!-- <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>
        </div>      -->
        <!--/span-->
      </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/profiles/new.html.erb
<h1>Hello World</h1>

app/views/yelps/_lookup.html.erb
<div class="container bg-no-overlay">
  <div class="row text-center">
    <h1>Never Plan</h1>
    <br><br>
  </div>
</div>

<%= form_tag search_path, method: :get do %>
<div class="form-group">
<%= label_tag "Keyword" %>
<%= text_field_tag :term,nil,placeholder: 'Enter keyword', class:'form-control' %>
<br>
<%= label_tag "Location" %>
<%= text_field_tag :location, nil, placeholder:'Enter Location', class:"form-control" %>

</div>
<br>
<%= button_tag "Search", class: 'btn btn-success', type:'submit' %>
<% end %>

app/views/yelps/index.html.erb
<div class="card-deck">
          <% @yelps.each do |business| %>
            <div class="card">
              <%= image_tag(business["image"], class:"card-img-top") %>
                <div class="card-block">
                  <h4 class="card-title">
                    <%= business["name"] %>
                  </h4>
                  <p class="card-text">Address:
                    <%= business["address"] %>
                  </p>
                  <p class="card-text">Phone:
                    <%= business["phone"] %>
                  </p>
                  <p class="card-text">Review Count:
                    <%= business["review_count"] %>
                      <p>
                  <!-- <p class="card-text">Rating:
                    <%= business["rating"] %>
                      <p> -->
                </div>
                <!-- <div class="card-footer">
                  <%= link_to "Check them out on Yelp", business["url"], class:"card-link text-muted" %>
                </div> -->
                <hr>
                <%= button_to "Delete", {:controller => :yelps, :action => "destroy", yelp_id: business.id }, :method => :delete, class: 'btn btn-danger' %>
            </div>
            <% end %>
      </div>

app/views/yelps/search.html.erb
<%= render 'lookup' %>
<!-- <%= @response.to_json %> -->
  <div class="card-deck">
    <% if @response.present? && !@response['businesses'].nil? %>
      <% @response["businesses"].each do |result| %>
        <div class="card">
          <%= image_tag(result["image_url"], class:"card-img-top") %>
            <div class="card-block">
              <h4 class="card-title">
                <%= result["name"] %>
              </h4>
              <p class="card-text">Address:
                <%= result["location"]["display_address"][0] %>
              </p>
              <p class="card-text">Phone:
                <%= result["display_phone"] %>
              </p>
              <p class="card-text">Rating:
                <%= result["rating"] %>
                  <p>
            </div>
            <div class="card-footer">
              <%= link_to "Check them out on Yelp", result["url"], class:"card-link text-muted" %>
            </div>
            <hr>
            <!-- <%= result %> -->
            <%= form_tag yelps_path, method: "post" do |f| %>

              
                <%= hidden_field_tag "result[phone]", result["display_phone"]  %>
                  <%= hidden_field_tag "result[address]", result["location"]['city']  %>
                    <%= hidden_field_tag "result[name]", result["name"] %>
                    <%= hidden_field_tag "result[image]", result["image_url"] %>
                    <%= hidden_field_tag "result[price]", result["price"] %>
                    <%= hidden_field_tag "result[review_count]", result["review_count"] %>
                      <%= button_tag "Save to my profile", type:"submit", class:"btn btn-success" %>
                        <% end %>
        </div>
        <% end %>
          <% end %>
  </div>